services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4318:4318"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:16686"]
      interval: 30s
      timeout: 10s
      retries: 5

  consul:
    image: hashicorp/consul:1.10.0
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 30s
      timeout: 10s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.9.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  db-chat:
    image: postgres:14-alpine
    container_name: translatify-db-chat
    env_file: "./chat/.env"
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres/chat-data:/var/lib/postgresql/data

  db-user:
    image: postgres:14-alpine
    container_name: translatify-db-user
    env_file: "./user/.env"
    ports:
      - "5433:5432"
    volumes:
      - ~/apps/postgres/user-data:/var/lib/postgresql/data

  chat:
    build:
      context: .
      dockerfile: chat/Dockerfile
    env_file: "./chat/.env.docker"
    ports:
      - "54500:54500"
    depends_on:
      - jaeger
      - consul
      - rabbitmq
      - db-chat

  user:
    build:
      context: .
      dockerfile: user/Dockerfile
    env_file: "./user/.env.docker"
    ports:
      - "50052:50052"
    depends_on:
      - jaeger
      - consul
      - rabbitmq
      - db-user

  translation:
    build:
      context: .
      dockerfile: translation/Dockerfile
    env_file: "./translation/.env.docker"
    ports:
      - "4200:4200"
    depends_on:
      - jaeger
      - consul
      - rabbitmq
      - db-chat

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    env_file: "./gateway/.env.docker"
    ports:
      - "8080:8080"
    depends_on:
      - jaeger
      - consul
      - rabbitmq
      - db-chat